### ISSUE TITLE
BEASTv1.10.1 limit the predictors quantities

### ISSUE THREAD

**Issue by xiayh17** [beast-dev/beast-mcmc#1025]
Hi，
I set GLM use BEAUti v1.10.1 and there are 19 predictors. The BEAST report an error ,seems can't found the id in glmmodel. But when I delete the predictor numbers <= 9, BEAST can run right.
this is my file before and after delete predictors numbers.
https://drive.google.com/open?id=18XM6am9xn0OY7QLPh6kV059_357L5QKW
How can i solve this problem?
Thanks.

**Comment by GuyBaele** [comment]
This error message indeed indicates that the GLM was not parsed correctly, but not because there would be a limit to the number of possible predictors. The underlying problem is that the matrix of independent variables you have provided is not identifiable for your XML with 19 predictors; there is no problem with identifiability in your GLM with 9 predictors.

I have now modified the messaging of the GLM to print to screen when there is an identifiability issue.

**Comment by sungml92** [comment]
Hi,

I know this is closed topic; however, I am experiencing similar problem. 

After I finished reviewing GLM workshop, I wanted to set-up my own analysis. I added 19 predictors using BEAUTIv1.10.4 and run the xml file with BEASTv1.10.4. The error message below indicates that my BEAST file is poorly formed and is terminated without running. However, it also says "Total # of predictors = 19 and rank = 15, Provided matrix of independent variables is not identifiable". I was not sure how to resolve this problem at first; and therefore, I just deleted random independent predictor matrix from xml (from n=19 to n=15). Then suddenly BEAST ran although i did not make further changes. 

Is there a limit on how many predictors I can put in one GLM?

-----------------
	Adding independent predictors 'location.coefficients' with design matrix 'location.designMatrix'
	Total # of predictors = 19 and rank = 15
	Provided matrix of independent variables is not identifiable.

	BEAST has terminated with an error. Please select QUIT from the menu.
	Apr 11, 2019 11:42:03 PM dr.app.beast.BeastMain <init>
	SEVERE: Parsing error - poorly formed BEAST file, GLM_test.xml:
	Error parsing '<glmModel>' element with id, 'null':
	'id' attribute was not found in glmModel element.

	Error thrown at: dr.xml.XMLObject.getAndTest(Unknown Source)
-----------------

Cheers,
Sung

**Comment by maxbiostat** [comment]
Please see [this](https://www.cds.caltech.edu/~murray/amwiki/index.php/FAQ:_What_does_it_mean_for_a_non-square_matrix_to_be_full_rank%3F) for an explanation of what "full rank" means. 

The predictor matrix being full rank is a necessary condition for fitting a GLM, lest one runs into computational problems due to singularities.

**Comment by sungml92** [comment]
@maxbiostat 
This clarifies a lot. Thank you!
