### ISSUE TITLE
Tree prior generation has failed: Index 5 out of bounds for length 5

### ISSUE THREAD

**Issue by niconm89** [beast-dev/beast-mcmc#1113]
Hi, I'm trying to generate a matrix file using beauti but I got an error in the final step.

Here are the steps I'm following.

1) I have 51 partitions (12 taxa), I have only selected unlink site models, link clock model and link trees.

2) I selected a specific site model for each partition

3) I selected an uncorrelated relaxed clock with a lognormal distribution

4) I selected 'Speciation: Birth-Death Process' as Tree prior

5) I define a molecular clock in the Priors section

Finally, when I click on generate BEAST file, I got the error "The BEAST XML is incomplete because: Tree prior generation has failed: Index 5 out of bounds for length 5"

I tried to fix it by deleting some partitions and choosing other Tree priors but nothing changed.

I appreciate any help you can give me.

Nicolás

**Comment by niconm89** [comment]
Thank you Guy, I built a beast.jar and now it is working.

**Comment by LesterJP** [comment]
Hi, Guy I am trying ot generate the XML to perform a phylogeographic analysis using the travel history model, every time 
I tried to generate the XML using beauti 1.10.5pre_thorney_0.1.1
 I got an error in the final step.

He "The BEAST XML is incomplete because Taxon list generation has failed: Index 5 out of bounds for length 5"
I appreciate any help you can give me.
Lester

**Comment by v-julia** [comment]
> 

Hi, Guy.

I have the same error. In some of my sequences there is no info on sampling day, so I use parsing calendar dates with variable precision. No partition into codon position, strict clock. I need 'Speciation: Birth-Death Process'  tree prior for my analysis, but I also tried the other ones. And every time I am getting "The BEAST xml is incomplete because: Taxon list generation has failed: 5".  Am I doing something wrong?

v1.10.5pre_thorney_v0.1.2
Windows 10
