### ISSUE TITLE
Low ESS value for treeModel.rootHeight, age(root) and treeLength estimated by BEASTv.1.10.5pre_thorney_v0.1.1

### ISSUE THREAD

**Issue by Being-Li** [beast-dev/beast-mcmc#1140]
Hi! I analyzed a large phylogenetic dataset fowlling the tutorial [https://beast.community/thorney_beast].
But I got very low ESS values for some parameters, I don't know why. I tried to change the Weight, but it didn't work. What can I do to solve this problem? 
Thank you！

In the xml file these parameters are set like this:
(startingTree and dataTree are specified as an ML tree built by FastTree)

	<constrainedTreeModel id = "treeModel">
		<tree idref="startingTree"/>
		<constraintsTree>
			<tree idref="dataTree"/>
		</constraintsTree>
	</constrainedTreeModel>
	
	<treeHeightStatistic id="treeModel.rootHeight">
		<treeModel idref="treeModel"/>
	</treeHeightStatistic>
	
	<treeLengthStatistic id="treeLength">
		<treeModel idref="treeModel"/>
	</treeLengthStatistic>
	
	<tmrcaStatistic id="age(root)" absolute="true">
		<treeModel idref="treeModel"/>
	</tmrcaStatistic>

	<operators id="operators" optimizationSchedule="log">
		<nodeHeightOperator type="uniform" weight="30">
			<treeModel idref="treeModel"/>
		</nodeHeightOperator>		
		<nodeHeightOperator type="scaleRoot" weight="30" scaleFactor="0.75" >
			<treeModel idref="treeModel"/>
		</nodeHeightOperator>		
		<uniformSubtreePruneRegraft weight="30">
			<constrainedTreeModel idref="treeModel"/>
		</uniformSubtreePruneRegraft>
		<narrowExchange weight="30">
			<constrainedTreeModel idref="treeModel"/>
		</narrowExchange>		
		<wideExchange weight="30">
			<constrainedTreeModel idref="treeModel"/>
		</wideExchange>		
		<wilsonBalding weight="30">
			<constrainedTreeModel idref="treeModel"/>
		</wilsonBalding>
	</operators>

![1666583081114](https://user-images.githubusercontent.com/56345385/197464640-7b85688e-9852-4843-90d6-251766e67715.jpg)
![1666583090962](https://user-images.githubusercontent.com/56345385/197464648-bb3afe18-4200-4032-a259-05d5bd00445f.jpg)
![1666583103684](https://user-images.githubusercontent.com/56345385/197464654-5620fe10-2c62-4c70-ae74-957ec06cef1a.jpg)

**Comment by jtmccr1** [comment]
Hello, 

I have seem somewhat similar behaviour in certain datasets. I believe it's caused by an interaction between the tree and coalescent prior which makes mixing difficult. In the case of these large analyses the topological constraints in the tree exasperate this issue. It's hard to know without seeing the data but I would expect the root is getting "trapped" between a few gridpoints, and sampling between these modes is challenging. 

If it makes sense in your analysis, you could try to use fewer gridpoints in the skyline. I'd be happy to follow up more offline it would be helpful.
