### ISSUE TITLE
Skyride reconstruction broken in Tracer 1.6

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#744]
Originally reported on Google Code with ID 737

```
If I try to reconstruct a skyride plot in Tracer 1.6 all I get is a progress bar that
never advances.
```

Reported by `mdhall272` on 2014-06-26 13:46:14

**Comment by msuchard** [comment]
@mdhall272, has this been fixed?  Could you check?

**Comment by twoseventwo** [comment]
It works I if run TracerApp within BEAST, but not using the Tracer standalone that @rambaut has on his site. Has the code been tinkered with since the latter was uploaded?

(Actually, it works fine on a very short log file. So perhaps it's just very slow - but if so then it's much, much slower than Tracer 1.5.)

**Comment by twoseventwo** [comment]
(This is Mac, by the way.)
