### ISSUE TITLE
Include handy ways of importing taxon sets (through Nexus or a text file).

### ISSUE THREAD

**Issue by rambaut** [beast-dev/beast-mcmc#916]
'm trying to get taxon sets into Beauti. I have 563 taxa so defining sets within beauti is painstaking, as is listing taxon names in each set in the nexus file. Does beauti not recognize ranges of taxa, as per:

end;

BEGIN SETS;
CHARSET Cytb = 1-1140;
TAXSET Afro = 3-29;	
TAXSET Carn =30-256;	
TAXSET Ceta = 257-520;	
TAXSET toot= toot=448-520;
TAXSET Ingr=3-563;

end;

**Comment by rambaut** [comment]
Implemented this as importing from a text file. It is either one column with a set of taxon labels (the name of the set comes from the file name) or 2 columns with taxon label in the first and set name in the second.

**Comment by rambaut** [comment]
Also implemented loading 'taxset' in Nexus.

**Comment by noranekonobokkusu** [comment]
Hello,

it seems that the 'Import taxon sets' option in beauti doesn't work in v.1.10.4. It results in a corrupted xml file and an error 'dr.app.beauti.generator.Generator$GeneratorException: TMRCA statistics generation has failed:
Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.Map.get(Object)" is null
'.

I checked that on the file from the tutorial http://beast.community/rates_and_dates by creating manually a text file with a list containing some of the taxa. It's uploaded properly and looks fine in beauti but results in the same exception while saving the xml-file. Specifying taxon sets directly in beauti works both on my dataset and on the file from the tutorial.
